### ISSUE TITLE
License

### ISSUE THREAD

**Issue by umeboshi2** [bechtoldt/iscdhcp-formula#3]
I just read your license.  This was just a side effect of performing a diff against the other formula [here](https://github.com/saltstack-formulas).  Is this behavior allowed and acceptable on [GitHub](https://github.com)?

**Comment by bechtoldt** [comment]
Please feel free to do any apache-compatible work with my formulas on Github. 

The only intention behind the extra clause is that I want people to keep the fork path on Github.

What do you mean with "Is this behavior allowed and acceptable on GitHub?"?

**Comment by umeboshi2** [comment]
I like what I have seen with the formulae you have been posting.  I took the time to add my experience with managing netboot clients in the config.  You can have all my code that's sitting here on github, as well as berlios, sourceforge, etc.  Don't take my issue the wrong way, but I have an expectation to be able to make a fork and not have to write code very similar to what you have already done.

**Comment by bechtoldt** [comment]
You want to fork my formulas on Github? Feel free!

Why should be there issues with that? I think everything looks fine.

**Comment by umeboshi2** [comment]
The (license)[https://github.com/umeboshi2/iscdhcp-formula/blob/master/LICENSE], or this part here:
```
ECCEPTIONS:
You MAY NOT upload parts or the whole work of this product on Github or
any other platform again UNLESS you are in possession of an agreement
by the author OR use the function called "FORK" provided on Github itself.
Other parts of the specified license above are not affected.
```

I am not only going to fork this on github, but this code will sit on servers that will providing netboot services to the machines that I have to keep running.

Also, I've been using `git subtree` to put all my formulae in a single repository to make it easier to manage. (not only easier, but I have lost code with an `rm` by "thinking everything was updated."

Anyway, I was trying to get my stuff in order and look over the files again when I took the time to read the license.  Did you write the license?

**Comment by bechtoldt** [comment]
> I am not only going to fork this on github, but this code will sit on servers that will providing netboot services to the machines that I have to keep running.

Do it, it's okay. As I already said: The only intention of the extra clause is to prevent people from republishing code without keeping the credits to the initial author or forking code on Github without using the fork feature on Github like the salt-formulas guys do (which is a workflow that I don't like).

> Also, I've been using git subtree to put all my formulae in a single repository to make it easier to manage. (not only easier, but I have lost code with an rm by "thinking everything was updated."

That's cool. If it's easier for you, just create a new empty Git repository and collect all the code there. You don't need to keep the fork path to https://github.com/bechtoldt/saltstack-template-formula on https://github.com/umeboshi2/saltstack-formulae. Simply create a file AUTHORS (or similar) and add ``Arnold Bechtoldt <mail@arnoldbechtoldt.com> (https://github.com/bechtoldt/)``. Then you have a tree of formulas/ SLS directories and a place for any copyleft.

This way you should have a Git repo that is much cleaner.

> Anyway, I was trying to get my stuff in order and look over the files again when I took the time to read the license. Did you write the license?

Sure, I wrote those lines.

I hope that I could help you with my thoughts.



By the way:

I use the following script to sync the folders of formulas with my private states repo that is used by the Salt masters:

```
#!/bin/bash

formulas=~/Documents/dev/formulas/github
fdir=~/Documents/dev/salt-infra/salt-env

for d in ${formulas[@]}/*-formula; do
  echo ============
  formula="${d##*/}"
  formula="${formula%*-formula}"
  formula_prefix=''

  if [[ "$formula" =~ saltstack-* ]]; then
    formula="${formula#saltstack-*}"
    formula_prefix='saltstack-'
  fi

  echo Formula: $formula

  rsync --delete -q -a ${formulas}/${formula_prefix}${formula}-formula/${formula}/ ${fdir}/${formula}/
done

echo -e "\n"
```

This script has some downsides but it's okay for most of my time.

**Comment by umeboshi2** [comment]
OK.  Sorry for the confusion.  I created an AUTHORS file and put you in there like you said.  I suppose that it doesn't make sense to keep a fork to the template repo, but it was a pretty good place to start putting this stuff together.

I just want to be clear that I don't feel that using "git subtree" in the manner that I am doing is strictly in compliance with the terms of your license, and without conversing with you, I would feel that I am in violation of the license.  Thanks! :+1:

**Comment by bechtoldt** [comment]
Alright, cool!
